### ISSUE TITLE
`npm run serve` gives an empty page

### ISSUE THREAD

**Issue by JaSpa** [thomashoneyman/purescript-halogen-realworld#118]
Cloning this repository and running `npm run serve` from inside of the nix shell results in an empty page.

The problem is that `index.html` refers to **main**.js instead of **index**.js. However, `npm run bundle` is configured to produce a **main**.js file.

* `index.js` should be moved to `main.js`, *or*
* `index.html` and `package.json` should be adjusted to create/refer to `index.js` instead of `main.js`

**Comment by thomashoneyman** [comment]
Thanks for catching this! This does need to be fixed.
