### ISSUE TITLE
Build Fails when I update to the latest package sets: Error found: in module Conduit.Data.Profile

### ISSUE THREAD

**Issue by harryprayiv** [thomashoneyman/purescript-halogen-realworld#123]
When I attempt to update the package sets to the latest (https://github.com/purescript/package-sets/releases/download/psc-0.15.14-20240118/packages.dhall), I get the following error:

`[ 1 of 24] Compiling Conduit.Data.Profile
Error found:
in module Conduit.Data.Profile
at src/Data/Profile.purs:26:20 - 26:28 (line 26, column 20 - line 26, column 28)

  Cannot import value mapCodec from module Data.Codec
  It either does not exist or the module does not export it.`
  
This is obviously because the Data.Codec module was massively simplified.  I attempted to fix it but it was **far** beyond my current skill level.  I'd like to use the latest package set to build this project. If possible, I'd love to help refactor this application to take advantage of the latest package sets.  Thanks for sharing this super-important example for the Purescript ecosystem.

**Comment by thomashoneyman** [comment]
Fortunately it's not too hard! You can replace `mapCodec` by inserting calls to decode / encode and constructing a new basic codec, like this:

```patch
-authorCodec mbUsername = CA.mapCodec to from codec
+authorCodec mbUsername = CA.codec' (to <=< CA.decode codec) (CA.encode codec <<< from)
```

**Comment by thomashoneyman** [comment]
I went ahead and updated this repo to a new package set and to use the new spago@next releases. Thanks for the reminder!

**Comment by harryprayiv** [comment]
Thanks for the quick fix!  I'm having such a great time putting all of my energy into the Purescript ecosystem; thankful to be able to stand on the shoulders of generous giants like you and the rest of Purescript's contributors.

**Comment by thomashoneyman** [comment]
Welcome! Enjoy the journey!
