### ISSUE TITLE
Real World Demo

### ISSUE THREAD

**Issue by jacekschae** [thomashoneyman/purescript-halogen-realworld#21]
Hi there,

I'm putting togeterh a refresh of [Real World Comparision of Front-End Frameworks](https://medium.freecodecamp.org/a-real-world-comparison-of-front-end-frameworks-with-benchmarks-2018-update-e5760fb4a962) and was wondering if you could put a link to a demo application (on Netlify or something) into the repo? This is needed for the first metric--Performance.

if this is not imporatnt to you -- that is also fine and feel free to close this issue.

Thanks, Jacek

**Comment by JordanMartinez** [comment]
I'm not Thomas, but I'd be interested in seeing the results.

**Comment by thomashoneyman** [comment]
Hi @jacekschae! I’m glad to see a refresh to the article for 2019. At the moment I am quite busy; putting a bundle together to serve via Netlify for a demo is a little lower priority than a few other tasks I need to take care of in my free time. I do plan to do so soon, but if I don’t make the cutoff for your article, perhaps a simple note stating that this repository didn’t have a live demo at the time of writing would do. 

I am closing this for now, but when I get the demo up I’ll update this thread.

**Comment by wryk** [comment]
Do you want help with that one ? I understand this might be not the kind of task you want to delegate.
Maybe an unofficial demo can do the job until you got time to setup an official one ?

Because the lacks of demo this implementation was skipped since 2019 and I would like to see purescript + halogen in the 2021 realworld frontends comparison.

**Comment by thomashoneyman** [comment]
With GitHub Actions it’s now very easy to publish to GitHub pages (Formless does this). And with setup-PureScript it’s easy to get zephyr in CI for the bundle. So I think this is an achievable task if you would like to help, @wryk, by adding a new GitHub pages workflow for publishing!

@milesfrain had some interesting results wrt bundling with Zephyr and Parcel and so I’d appreciate his input when you do this as well. Want to make a new issue for this and I’m happy to answer any questions along the way?

**Comment by wryk** [comment]
Alright I'll do that. I'll look at your suggestions and try them on my fork. I'll submit a PR when I think that's good enough to reviewed.

I saw @milesfrain results on Zephyr repo and discourse, I'll take them into account.

**Comment by thomashoneyman** [comment]
You would use something like this workflow:

https://github.com/thomashoneyman/purescript-halogen-formless/actions/runs/203471748/workflow

But you'd switch the command to produce the bundle to what's used for this project:

https://github.com/thomashoneyman/purescript-halogen-realworld/actions/runs/203470953/workflow#L56

And you'd deploy the resulting bundle in `dist` to `gh-pages`. Let me know if I can help further!
