### ISSUE TITLE
Update for Halogen 5

### ISSUE THREAD

**Issue by thomashoneyman** [thomashoneyman/purescript-halogen-realworld#25]
Halogen is on its [fourth release candidate](https://github.com/slamdata/purescript-halogen/releases/tag/v5.0.0-rc.4) for v5, which appears imminent once docs are updated. [Formless](https://github.com/thomashoneyman/purescript-halogen-formless), the only Halogen dependency of this project, is updated for Halogen 5. As far as I'm aware the only other missing dependency is `RemoteData`, which has conflicting versions for `Lens`.

This project should be updated for Halogen 5 as soon as possible, where it can serve as a migration guide for others upgrading to Halogen 5 in the near future.

**Comment by JordanMartinez** [comment]
You might want to update your guide to point to my `learn-halogen` repo now. Here's the announcement: https://discourse.purescript.org/t/learn-halogen-v1-0-0-release/764

**Comment by thomashoneyman** [comment]
Thanks @JordanMartinez, I'll keep that in mind when I update the content for release.
