### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by evanrelf** [thomashoneyman/purescript-halogen-realworld#30]
- `cayabilities -> capabilities`
  https://github.com/thomashoneyman/purescript-halogen-realworld/blob/d213795014a69af99dcb90cdbc8628d3f760c171/src/AppM.purs#L64

- `manageCommentAppm -> manageCommentAppM`
  https://github.com/thomashoneyman/purescript-halogen-realworld/blob/6836de104c29dfd3fc8625061fad8d83f4dc55dd/src/AppM.purs#L250

- Add space after period (`details.When`)
  https://github.com/thomashoneyman/purescript-halogen-realworld/blob/6836de104c29dfd3fc8625061fad8d83f4dc55dd/src/Api/Request.purs#L94

**Comment by thomashoneyman** [comment]
Thanks @evanrelf for finding these! I'm sorry I took so long to get back to you -- things are a bit hectic right now -- and this is now fixed.

**Comment by evanrelf** [comment]
No worries. Thanks for making this project; it's been really helpful to reference as I learn PureScript!
