### ISSUE TITLE
Installation instructions in Readme outdated

### ISSUE THREAD

**Issue by mjepronk** [thomashoneyman/purescript-halogen-realworld#38]
I think the installation instructions in the Readme are outdated, the commands `yarn build-serve` or `yarn watch-dev` do not work. Should we use `spago` instead of `yarn` now?

**Comment by thomashoneyman** [comment]
@mjepronk Thanks for bringing this to my attention -- you're right, those commands are outdated. They should be something like `yarn install`, then `yarn build`, then `yarn serve`. I'll update them as soon as I can!

Yarn is used to download JavaScript dependencies (like the Marked library), and to run scripts from `package.json`. Some of those include:

- `build` -> runs `spago build` to build the project
- `bundle` -> runs `spago bundle-app --main Main --to dist/app.js` and then `parcel build assets/index.html` to get distribution-ready js
- `serve` -> runs the bundle step, `bundle`, and then `http-server dist` to serve the app

Yarn and Spago are therefore compatible, not mutually-exclusive; I use yarn to run a few specific scripts leveraging Spago.

**Comment by mjepronk** [comment]
Aah, great thanks! You want me to do a PR for the Readme? :-)

**Comment by thomashoneyman** [comment]
Sure, if you don’t mind!

**Comment by mjepronk** [comment]
Not at all, thank you for your excellent PureScript articles!

**Comment by thomashoneyman** [comment]
Closed by #39
