### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by RAbraham** [thomashoneyman/purescript-halogen-realworld#4]
I cannot express enough my gratitude for this work. I feel like I may have saved a few months of learning FP just by reading your excellent explanation and code.
PureScript by Example and this resource are the bare minimum that I would recommend any newcomer to PureScript. 
Thanks a ton!

**Comment by thomashoneyman** [comment]
Thank you, Rajiv! I really appreciate hearing that. I've still got a ways to go until this is a legitimate demonstration of a Halogen application, but I'm delighted to hear it's already useful. Please let me know if you come across any issues as you keep going through it that I can resolve -- this is all still a rough draft :)
