### ISSUE TITLE
Question about conduit.productionready.io

### ISSUE THREAD

**Issue by joshcough** [thomashoneyman/purescript-halogen-realworld#42]
Hi, sorry for asking a question here, but wasn't sure the best place to do it. I'm looking to find the backend code for `conduit.productionready.io`, because I can't really put this whole thing together as an example application without it. Like, I would really like to try this out on my own, get up my own server and use this as a launchpad, but yeah, just isn't possible without the backend code. Please let me know.

**Comment by thomashoneyman** [comment]
Hi @joshcough! Feel free to ask questions here 👍 

This repository is one of many frontend implementations of the [Real World project](https://github.com/gothinkster/realworld). There are [several backend implementations, too](https://github.com/gothinkster/realworld#backends). The idea is that you can compare different frontend and backend languages / libraries.

If you'd like to try this on your own, set up a server, and expand on the features, then I'd recommend choosing whichever backend implementation you like most and match them together.

Closing the issue as this project has no opinion on backend code, but feel free to reach out if you have further questions on this or other topics.

**Comment by joshcough** [comment]
@thomashoneyman thank you!
