### ISSUE TITLE
yarn install fails due to invalid link in halogen-formless

### ISSUE THREAD

**Issue by skress** [thomashoneyman/purescript-halogen-realworld#43]
Hi,

thanks a lot for this example project it is really helpful. I have just tried installing a fresh copy and it fails during `yarn install`:

```
spago: Installation failed.
Error:
Invalid file name in tar archive: "../bower_components/purescript-halogen-storybook/examples/src/Storybook.css"
error Command failed with exit code 1.
```

Running `spago install -v` shows a bit more context:
```
About to fetch tarball for https://github.com/thomashoneyman/purescript-halogen-formless/archive/v1.0.0-rc.1.tar.gz
Fetching https://github.com/thomashoneyman/purescript-halogen-formless/archive/v1.0.0-rc.1.tar.gz
spago: Installation failed.

Error:

Invalid file name in tar archive: "../bower_components/purescript-halogen-storybook/examples/src/Storybook.css"
```

So the problem is that `halogen-formless` contains a link to `bower_components` which does not exist in the source repository. I am not sure if `spago` should ignore this type of error or if `halogen-formless` should create the link only after `bower` has populated that directory - or if there is even another approach.

**Comment by tarsbase** [comment]
I have the same problem. Does anyone know how to fix it?

**Comment by skress** [comment]
As a quick fix you can manually install halogen-formless.

Inside `purescript-halogen-realworld` directory (after having run `yarn install`):
```bash
wget https://github.com/thomashoneyman/purescript-halogen-formless/archive/v1.0.0-rc.1.tar.gz
cd .spago/
tar xvf ../v1.0.0-rc.1.tar.gz
mv purescript-halogen-formless-1.0.0-rc.1 halogen-formless/v1.0.0-rc.1
cd ..
rm v1.0.0-rc.1.tar.gz
yarn install
```

**Comment by thomashoneyman** [comment]
This is odd; Formless relies on Storybook as a dev dependency, but I don't know why installing the library would make any attempt to bring in Storybook or refer to its CSS file. I will try to investigate this tonight and put up a fix as soon as possible. Thanks @skress for bringing this to my attention and providing a manual fix for the time being!

**Comment by thomashoneyman** [comment]
Thanks @skress and @gho0sts for helping out with this issue. I've fixed the problem in https://github.com/thomashoneyman/purescript-halogen-formless/pull/55. 

You should now be able to install everything normally with `spago install`. Let me know if there are any further issues, though!
