### ISSUE TITLE
Thank you again!

### ISSUE THREAD

**Issue by baig** [thomashoneyman/purescript-halogen-realworld#47]
This is extremely useful and I cannot express my gratitude enough for your efforts. I'm sure so many others feel the same.

Thank you for sharing this with the world.

This issue was not created to complain or report anything, so you can close this any time.

**Comment by thomashoneyman** [comment]
Thanks @baig! It’s wonderful to read this. Please don’t hesitate to reach out if there are any other ways I can help out 😊

https://thomashoneyman.com/open-invitation
