### ISSUE TITLE
Would you be interested in a PR to update various dependencies?

### ISSUE THREAD

**Issue by kurtmilam** [thomashoneyman/purescript-halogen-realworld#49]
The application builds and runs locally after I:

1. Update the `dependencies` and `devDependencies` in `package.json`
2. Update the `spago` package set
3. Update the `halogen` override to `v5.0.0-rc.7`
4. Make a few changes to adapt to the new `request` API introduced with AffJax 10.0

I checked the additions defined in `packages.dhall`, and each seems to be on the latest version, so I think the above changes are all that's necessary to bring the project up to the latest state.

Thanks for sharing this project (and for the other writing and OSS work you do). I've found your writing and repos very helpful as I've been learning PureScript.

**Comment by thomashoneyman** [comment]
@kurtmilam Thanks for the kind words, and I would absolutely appreciate the update!

With regards to the `packages.dhall` it would also be useful to verify that the additions are still necessary. Some of those additions may now be in the official package set and can be removed.

**Comment by kurtmilam** [comment]
I will check to see whether any of the additions have been added to the latest package set 👍 !

**Comment by kurtmilam** [comment]
Good call on verifying the additions. Assuming I did everything correctly, it seems that `subcategory` is the only one not in the latest package set.
