### ISSUE TITLE
Change in url does not refresh the page

### ISSUE THREAD

**Issue by VerySmallRoach** [thomashoneyman/purescript-halogen-realworld#52]
Hello. I've build the project and run a local sever with yarn serve.
I've made two articles:
http://localhost:8081/?#/article/aaa-6umu5b
http://localhost:8081/?#/article/bbb-wvj44m
When I open two pages in two separate tabs, everything works.
However, if I open first page and then manually edit url to the second one, the page content remains unchanged. It only happens when I move from one article to another - if, for example, I open http://localhost:8081/?#/settings and then edit url to http://localhost:8081/?#/article/bbb-wvj44m, page content will be updated.

Unless I have some serious misunderstanding of how routing in SPA supposed to work, this looks like a bug. Any thoughts?

**Comment by VerySmallRoach** [comment]
I tried to look into it, and it seems like ViewArticle should handle a Receive event.
Something like this:
```purescript
Receive input -> do
      st <- H.get
      when (st.slug /= input.slug) do
        H.put $ initialState input
        handleAction Initialize
```

Is there a more idiomatic way to tell Halogen to recreate component on input change?
And I wonder whenever it is necessary to do an equality check. I'd expect Halogen to send Receive only when parameter had changed, but I can't find any confirmation in docs.

**Comment by thomashoneyman** [comment]
Hi @VerySmallRoach! You're right, if changing the URL on the page doesn't change its contents then that's a bug. And given that the URL is provided as component input then you're right that the receiver is the way to handle new input -- that's quite an oversight on my part to not have that done automatically.

Halogen will only send new input when the input has changed, that's correct. 

* If you always want to update the component state when the input changes then you can unconditionally handle the `Receive` action.
* If you want to update the component state only when some sub-part of the input changes (ie. given `{ name :: String, location :: Coordinate }` you only want to update if `name` changes) then you would guard the change with the check you used (`when (input.name /= state.name) ...`)

**Comment by thomashoneyman** [comment]
Two solutions come to mind:

1. Your solution should work -- when the slug changes, update the ViewArticle component
2. We can update global state + the subscription so that the slug is held globally, and any component which subscribes to changes in the slug automatically receives / re-renders when it changes.

If you're interested in trying either solution, I'd welcome a pull request. Otherwise I'll need to come back to this over the weekend to fix this.

Thanks for catching this and bringing it to my attention!

**Comment by VerySmallRoach** [comment]
Thank you for an explanation.

From the theoretical standpoint I agree that it would be nice if such reloading was automatic. I tried to experiment and wrote a component wrapper parametrized over two input types (first type made of everything that should trigger a reload, and second type contains the rest), and it even typechecks and works, but I have no idea how it would scale past two-pages-so-far project.

From more practical view, I don't think that such experimenting should be a part of a learning project like this, since it increases complexity over a little gain of value.

As for solutions you had proposed - I'm afraid I'm not familiar enough with the structure of Real World Halogen to attempt implementing second solution or to argue which solution is better (although storing slug globally sounds weird, how would it even work if we would decide to add a new page with two different slugs in route? Like /article/aaa/comment/bbb). So I'd rather leave it to you.

Thank you again for your time.

**Comment by Cmdv** [comment]
I literally came across this, my scenario is very similar:

(for me) I'm on `/pop/popA` and on that page I have a link to `/pop/popB` when clicked the URL changes but the component doesn't update.

I've been looking around router but and also in my component but I can't seem to get any values being emitted when I click the link.

```
PoPHome popName  ->
        HH.slot (SProxy :: _ "popHome") unit PoPHome.component { popName: popName} absurd
```

```
, "PoPHome": "pop" / popName segment
```

so on in `PoPHome.purs` I have an `Input` type with `popName` constructor but that never seems to come through even with a `Receive` 🤔 

It's a confusing one for sure, feels like it might be handled in `Router` but again I'm not 100%
