### ISSUE TITLE
Why Halogen?

### ISSUE THREAD

**Issue by Kurren123** [thomashoneyman/purescript-halogen-realworld#59]
In the “why Halogen?” Section in the introduction, you briefly state some other frameworks but you don’t specifically address the question of why Halogen. What has halogen got to offer that these other frameworks do not? I’m coming from Elm so I’m wondering whether I should put in the effort to learn halogen or stick with Spork, Hedwig, or another TEA done in purescript. 

Thank you for a great book so far.

**Comment by thomashoneyman** [comment]
Halogen differs from Elm in that it supports components with local state and can also use a global state across components. (I'm aware you can also implement the Elm architecture in Halogen, but I haven't tried this myself.)

At CitizenNet I worked on a Halogen app, and at Awake Security I work on a PureScript React app. In both cases, components helped ensure that state is kept where you actually reason about it and use it to produce UI, and that global state is kept uncluttered and minimal. I want to store things like the current user in global state, and I want to store things like which tab is focused in the panel in the sidebar in the component that actually cares about it.

This isn't an argument for Halogen; it's an argument for components with local state. I would personally choose PureScript React / Halogen over TEA done in PureScript for this reason. That said, if this doesn't really matter to you, there's no reason not to use Spork, Hedwig, Concur, etc.

Between Halogen and React the main decision, for me, is whether I want to interop with the React ecosystem or not. Using React under the hood can mean some surprising quirks and workarounds (for example: to deal with React's widespread use of referential equality), but the experience overall is pleasant, and at least I know if I need a charting library I can pull one off the shelf from React in a way that's not always true in Halogen.

So why Halogen? Halogen lets me use components, or skip them if I don't want them. It's 100% PureScript (with the [virtual dom library](https://github.com/slamdata/purescript-halogen-vdom) implemented in PureScript). The effect monad, `HalogenM`, has a really nice story for async code, forking threads in components, etc. You can freely intersperse your own type classes in code written in your components. And with [halogen-hooks](https://github.com/thomashoneyman/purescript-halogen-hooks) there's a nice way to write functions that use local state and reuse that stateful logic across many components.

I just don't see anywhere near the same flexibility + ability to reason about your code using other frameworks. I subjectively feel that when I write code in Halogen I get to push PureScript as far as it can go in a way that's not true with say PS-React or Elm clones. Unfortunately, that does carry an up-front cost in learning Halogen.

As a caveat: I don't have much experience with Elm or the Elm Architecture, so please feel free to correct me if I have made a mistaken assumption. I have written a small app using Elm, but as the state grew larger and it became tedious doing deep updates I moved to PureScript. However, I don't know how folks writing large Elm applications handle this problem and how satisfying the solutions are.

**Comment by Kurren123** [comment]
Thank you for a very detailed answer, it helped a lot. In Elm we try and keep things as flat as possible and try to grow the view (render) and state independently. Having said that, Halogen may open my eyes so I would like to give it a shot.

**Comment by thomashoneyman** [comment]
Great! Feel free to continue asking questions here.
