### ISSUE TITLE
Installation warnings

### ISSUE THREAD

**Issue by jamnut** [thomashoneyman/purescript-halogen-realworld#61]
Do I need to be concerned about any of the following?  I've done many years of systems level C development and have learned Haskell to maybe the novice level, but web development is new to me.

I'm assuming that the "No lockfile found" is not a problem, but what about all the warnings?

$ yarn install
yarn install v1.22.4
info No lockfile found.
[1/4] Resolving packages...
warning parcel-bundler > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning parcel-bundler > babylon-walk > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning parcel-bundler > @parcel/watcher > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning parcel-bundler > htmlnano > uncss > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning parcel-bundler > htmlnano > uncss > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning parcel-bundler > @parcel/watcher > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning parcel-bundler > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning parcel-bundler > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning purescript > purescript-installer > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning spago > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...

**Comment by thomashoneyman** [comment]
@jamnut I'm no NPM expert, but these look like fairly ordinary warnings in an ecosystem that moves as fast as JavaScript on the web. Tools like NPM and Yarn warn if there are known security issues in dependencies and I'm not seeing any of those warnings here. These warnings don't appear worrying.

Still -- I may as well not risk anything and stick to the latest versions I can! I'll go ahead and update these.
