### ISSUE TITLE
use Argonaut.Decoder.Decoders to drop Data.Argonaut.Decode.Struct.Tolerant

### ISSUE THREAD

**Issue by srghma** [thomashoneyman/purescript-halogen-realworld#67]
Doesn't with new release we are able to write custom decoders?

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/78e65c1928903534d1b5a3f69110f9c6212ec0d3/src/Data/Profile.purs#L98-L100

**Comment by thomashoneyman** [comment]
You could always write custom decoders (as described in the argonaut-codecs readme), but Tolerant Argonaut lets you customize that decoding and perform transformations on the result generically. It’s an in-between of the automatic decoding of the type classes and the manual decoding of hand-written decoders.

**Comment by srghma** [comment]
ok, then
