### ISSUE TITLE
Form `submit` event is not prevented 

### ISSUE THREAD

**Issue by wryk** [thomashoneyman/purescript-halogen-realworld#70]
The browser navigate the current page (from https://wryk.github.io/purescript-halogen-realworld/#/login to https://wryk.github.io/purescript-halogen-realworld/?#/login) when logging in, bypassing login app behavior and re-displaying the same login form. I can consistently reproduce this bug on both submit button click and enter keypress with Firefox 79 and Chromium 84 on the url without the empty query component (`?`).

This is because the app doesn't prevent native `submit` event behavior from the form (and instead rely on `click` event from the submit button to proceed with authentication). I can't explain why this is working when the url contains an empty query component.

The bug can be partially mitigated by using a button with `type=button` or properly by preventing default behavior of `submit` event. The later is usually the way forms are handled on SPA.

| Purescript Halogen Realworld | React Redux Realword |
| --- | --- |
| No event listener on form but one on submit button | No event listener on submit button but one on form, allowing .preventDefault() on its `submit` event |
| ![image](https://user-images.githubusercontent.com/1964408/91753179-d2731c80-ebc7-11ea-89c1-a817a8e0d44d.png) | ![image](https://user-images.githubusercontent.com/1964408/91752871-4b25a900-ebc7-11ea-919c-3b27ff68684a.png) |

Others form may also be concerned by this problem.

**Comment by thomashoneyman** [comment]
Whoops! Good catch. Yes, I think we should add a `preventDefault` for submission.

**Comment by wryk** [comment]
I started to tackle this issue but I don't know how to correctly avoid boilerplate code inside components actions. I may ask some help later for that.

**Comment by thomashoneyman** [comment]
Feel free to tackle this issue now, but as a heads up the forms will be switching to a new, Hooks-based version of Formless in the next month or two. Please go ahead if you'd like to, but the issue should be fixed then anyway :)

**Comment by wryk** [comment]
I have almost finished it but I don't see the point of integrating it if it is replaced right after. Thank you for letting me know.

I can't wait to see and learn the implementation with hooks :D

**Comment by toastal** [comment]
Shouldn't the Formless stuff validate on `<form onsubmit=...>` rather than overriding the `<button type=submit onclick=...>`?

**Comment by thomashoneyman** [comment]
Yes, that would be the better approach when using a `<form>` element. Formless doesn't care which event triggers a submission, so either will work.

**Comment by toastal** [comment]
I say this because I'm trying to do something similar and am lost in a type error with all the row stuff :(

**Comment by thomashoneyman** [comment]
I agree Formless is quite confusing. Fortunately for us all, the Hooks version of Formless is not far away and is considerably easier to use!
