### ISSUE TITLE
Not so clear where in Main.purs local storage is being used

### ISSUE THREAD

**Issue by flip111** [thomashoneyman/purescript-halogen-realworld#92]
About the main function documented is

> reading tokens from local storage

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/main/src/Main.purs#L3

I can not find the line of code where something with localstorage is done

**Comment by thomashoneyman** [comment]
The token is read here:

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/d1248699a148196b4e7760e8ebf592e4926236bf/src/Main.purs#L77

and the readToken function is defined here:

https://github.com/thomashoneyman/purescript-halogen-realworld/blob/d1248699a148196b4e7760e8ebf592e4926236bf/src/Api/Request.purs#L216-L219

**Comment by flip111** [comment]
Would you accept a PR with a comment above line 77 in Main.purs ?

**Comment by thomashoneyman** [comment]
Sure!
