### ISSUE TITLE
API Domain change

### ISSUE THREAD

**Issue by geromegrignon** [thomashoneyman/purescript-halogen-realworld#97]
Hello!

Due to governance changes, we are now using the `realworld.io` domain for the RealWorld demo (both client and API).
Requests from `conduit.productionready.io` are redirected to `api.realworld.io`, but such a redirection might lead to inconsistent responses.

We encourage domain change for the community.
If this repository is maintained anymore, we'll consider hosting a demo of your implementation in a few weeks with the domain change.

The demo link will be added to the RealWorld documentation.

**Comment by thomashoneyman** [comment]
Hi @geromegrignon -- this repository is maintained and I can update the API in the next few weeks. Is there anything that I need to do beyond making the update in this repository?

**Comment by geromegrignon** [comment]
Hey @thomashoneyman, thanks for the quick answer.
I created a related PR #98.

There is no required change besides **baseUrl**.
